# Generated by Django 4.0.6 on 2022-08-05 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_movement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='date_assigned',
            field=models.DateTimeField(db_column='date_assigned', default=datetime.datetime(2022, 8, 5, 9, 45, 41, 986557), verbose_name='Date assigned'),
        ),
    ]
