# Generated by Django 4.0.5 on 2022-07-11 16:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets_management', '0010_alter_atm_recorded_date_and_more'),
        ('assets_movement', '0002_branch_equitystore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='application',
            field=models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.systemhostedapplication', verbose_name='Hosted application'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assignee',
            field=models.ForeignKey(blank=True, db_column='assignee_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='atm',
            field=models.ForeignKey(blank=True, db_column='atm_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.atm', verbose_name='ATM'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='bio_avaya_note_gen',
            field=models.ForeignKey(blank=True, db_column='bio_avaya_note_gen_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.biovayanotecountergenerator', verbose_name='Bio/Avaya/note counter/generator'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='computer',
            field=models.ForeignKey(blank=True, db_column='computer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.computerlapdesktop', verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='date_approved',
            field=models.DateTimeField(db_column='date_approved', default=datetime.datetime(2022, 7, 11, 18, 22, 40, 765437), verbose_name='Date approved/rejected'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='date_assigned',
            field=models.DateTimeField(db_column='date_assigned', default=datetime.datetime(2022, 7, 11, 18, 22, 40, 765437), verbose_name='Date assigned'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='node',
            field=models.ForeignKey(blank=True, db_column='node_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.physicalnode', verbose_name='Physical node'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='printer_scanner',
            field=models.ForeignKey(blank=True, db_column='printer_scanner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.printerscanner', verbose_name='Printer/Scanner'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='screen',
            field=models.ForeignKey(blank=True, db_column='screen_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.screen', verbose_name='Screen'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='siwtch_router_firewall',
            field=models.ForeignKey(blank=True, db_column='switch_router_firewall_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.switchrouterfirewall', verbose_name='Switch Router Firewall'),
        ),
    ]
