# Generated by Django 4.0.6 on 2022-07-30 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_movement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='date_assigned',
            field=models.DateTimeField(db_column='date_assigned', default=datetime.datetime(2022, 7, 30, 10, 1, 41, 220766), verbose_name='Date assigned'),
        ),
    ]
