# Generated by Django 4.0.5 on 2022-07-11 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_movement', '0003_alter_assetassignment_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='date_approved',
            field=models.DateTimeField(db_column='date_approved', null=True, verbose_name='Date approved/rejected'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='date_assigned',
            field=models.DateTimeField(db_column='date_assigned', default=datetime.datetime(2022, 7, 11, 19, 1, 56, 979014), verbose_name='Date assigned'),
        ),
    ]
