# Generated by Django 4.0.6 on 2022-08-12 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_movement', '0005_alter_assetassignment_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='date_assigned',
            field=models.DateTimeField(db_column='date_assigned', default=datetime.datetime(2022, 8, 13, 1, 6, 55, 139169), verbose_name='Date assigned'),
        ),
    ]
