# Generated by Django 4.0.6 on 2022-08-05 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0002_alter_atm_recorded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='currect_exact_loc',
            field=models.CharField(blank=True, db_column='current_exact_loc', max_length=50, null=True, verbose_name='Current exact location'),
        ),
        migrations.AddField(
            model_name='atm',
            name='current_location',
            field=models.CharField(blank=True, db_column='current_location', max_length=40, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='biovayanotecountergenerator',
            name='currect_exact_loc',
            field=models.CharField(blank=True, db_column='current_exact_loc', max_length=50, null=True, verbose_name='Current exact location'),
        ),
        migrations.AddField(
            model_name='biovayanotecountergenerator',
            name='current_location',
            field=models.CharField(blank=True, db_column='current_location', max_length=40, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='computerlapdesktop',
            name='currect_exact_loc',
            field=models.CharField(blank=True, db_column='current_exact_loc', max_length=50, null=True, verbose_name='Current exact location'),
        ),
        migrations.AddField(
            model_name='computerlapdesktop',
            name='current_location',
            field=models.CharField(blank=True, db_column='current_location', max_length=40, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='physicalnode',
            name='currect_exact_loc',
            field=models.CharField(blank=True, db_column='current_exact_loc', max_length=50, null=True, verbose_name='Current exact location'),
        ),
        migrations.AddField(
            model_name='physicalnode',
            name='current_location',
            field=models.CharField(blank=True, db_column='current_location', max_length=40, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='printerscanner',
            name='currect_exact_loc',
            field=models.CharField(blank=True, db_column='current_exact_loc', max_length=50, null=True, verbose_name='Current exact location'),
        ),
        migrations.AddField(
            model_name='printerscanner',
            name='current_location',
            field=models.CharField(blank=True, db_column='current_location', max_length=40, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='screen',
            name='currect_exact_loc',
            field=models.CharField(blank=True, db_column='current_exact_loc', max_length=50, null=True, verbose_name='Current exact location'),
        ),
        migrations.AddField(
            model_name='screen',
            name='current_location',
            field=models.CharField(blank=True, db_column='current_location', max_length=40, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='switchrouterfirewall',
            name='currect_exact_loc',
            field=models.CharField(blank=True, db_column='current_exact_loc', max_length=50, null=True, verbose_name='Current exact location'),
        ),
        migrations.AddField(
            model_name='switchrouterfirewall',
            name='current_location',
            field=models.CharField(blank=True, db_column='current_location', max_length=40, null=True, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='which_store',
            field=models.CharField(choices=[('PROCUREMENT', 'PROCUREMENT'), ('IT', 'IT'), ('MUHANGA-DR', 'MUHANGA DRR'), ('NOT-IN-STORE', 'NOT IN STORE')], db_column='which_store', max_length=20, verbose_name='Which store'),
        ),
        migrations.AlterField(
            model_name='biovayanotecountergenerator',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='biovayanotecountergenerator',
            name='which_store',
            field=models.CharField(choices=[('PROCUREMENT', 'PROCUREMENT'), ('IT', 'IT'), ('MUHANGA-DR', 'MUHANGA DRR'), ('NOT-IN-STORE', 'NOT IN STORE')], db_column='which_store', max_length=20, verbose_name='Which store'),
        ),
        migrations.AlterField(
            model_name='computerlapdesktop',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='computerlapdesktop',
            name='which_store',
            field=models.CharField(choices=[('PROCUREMENT', 'PROCUREMENT'), ('IT', 'IT'), ('MUHANGA-DR', 'MUHANGA DRR'), ('NOT-IN-STORE', 'NOT IN STORE')], db_column='which_store', max_length=20, verbose_name='Which store'),
        ),
        migrations.AlterField(
            model_name='physicalnode',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='physicalnode',
            name='which_store',
            field=models.CharField(choices=[('PROCUREMENT', 'PROCUREMENT'), ('IT', 'IT'), ('MUHANGA-DR', 'MUHANGA DRR'), ('NOT-IN-STORE', 'NOT IN STORE')], db_column='which_store', max_length=20, verbose_name='Which store'),
        ),
        migrations.AlterField(
            model_name='printerscanner',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='printerscanner',
            name='which_store',
            field=models.CharField(choices=[('PROCUREMENT', 'PROCUREMENT'), ('IT', 'IT'), ('MUHANGA-DR', 'MUHANGA DRR'), ('NOT-IN-STORE', 'NOT IN STORE')], db_column='which_store', max_length=20, verbose_name='Which store'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='which_store',
            field=models.CharField(choices=[('PROCUREMENT', 'PROCUREMENT'), ('IT', 'IT'), ('MUHANGA-DR', 'MUHANGA DRR'), ('NOT-IN-STORE', 'NOT IN STORE')], db_column='which_store', max_length=20, verbose_name='Which store'),
        ),
        migrations.AlterField(
            model_name='switchrouterfirewall',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='switchrouterfirewall',
            name='which_store',
            field=models.CharField(choices=[('PROCUREMENT', 'PROCUREMENT'), ('IT', 'IT'), ('MUHANGA-DR', 'MUHANGA DRR'), ('NOT-IN-STORE', 'NOT IN STORE')], db_column='which_store', max_length=20, verbose_name='Which store'),
        ),
        migrations.AlterField(
            model_name='systemhostedapplication',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Recorded date'),
        ),
    ]
