# Generated by Django 4.0.5 on 2022-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0002_alter_biovayanotecountergenerator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='tag_number',
            field=models.CharField(blank=True, db_column='tag_number', max_length=40, null=True, verbose_name='Tag number'),
        ),
        migrations.AlterField(
            model_name='biovayanotecountergenerator',
            name='tag_number',
            field=models.CharField(blank=True, db_column='tag_number', max_length=40, null=True, verbose_name='Tag number'),
        ),
        migrations.AlterField(
            model_name='computerlapdesktop',
            name='tag_number',
            field=models.CharField(blank=True, db_column='tag_number', max_length=40, null=True, verbose_name='Tag number'),
        ),
        migrations.AlterField(
            model_name='physicalnode',
            name='tag_number',
            field=models.CharField(blank=True, db_column='tag_number', max_length=40, null=True, verbose_name='Tag number'),
        ),
        migrations.AlterField(
            model_name='printerscanner',
            name='host_ip',
            field=models.CharField(blank=True, db_column='host_ip', max_length=20, null=True, verbose_name='Host IP'),
        ),
        migrations.AlterField(
            model_name='printerscanner',
            name='tag_number',
            field=models.CharField(blank=True, db_column='tag_number', max_length=40, null=True, verbose_name='Tag number'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='tag_number',
            field=models.CharField(blank=True, db_column='tag_number', max_length=40, null=True, verbose_name='Tag number'),
        ),
        migrations.AlterField(
            model_name='switchrouterfirewall',
            name='tag_number',
            field=models.CharField(blank=True, db_column='tag_number', max_length=40, null=True, verbose_name='Tag number'),
        ),
    ]
