# Generated by Django 4.0.6 on 2022-08-12 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0003_atm_currect_exact_loc_atm_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 12, 9, 36, 24, 991752), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='biovayanotecountergenerator',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 12, 9, 36, 24, 991752), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='computerlapdesktop',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 12, 9, 36, 24, 991752), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='physicalnode',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 12, 9, 36, 24, 991752), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='printerscanner',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 12, 9, 36, 24, 991752), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 12, 9, 36, 24, 991752), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='switchrouterfirewall',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 12, 9, 36, 24, 991752), verbose_name='Recorded date'),
        ),
        migrations.AlterField(
            model_name='systemhostedapplication',
            name='recorded_date',
            field=models.DateTimeField(db_column='recorded_date', default=datetime.datetime(2022, 8, 12, 9, 36, 24, 998924), verbose_name='Recorded date'),
        ),
    ]
