# Generated by Django 4.0.5 on 2022-07-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0004_remove_physicalnode_service_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhostedapplication',
            name='vendor',
            field=models.CharField(blank=True, db_column='vendor', max_length=60, null=True, verbose_name='Vendor'),
        ),
    ]
