# Generated by Django 4.0.5 on 2022-07-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0005_systemhostedapplication_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhostedapplication',
            name='status',
            field=models.CharField(choices=[('WORKING-GOOD', 'WORKING GOOD'), ('WORKING-BAD', 'WORKING BAD'), ('NOT-WORKING', 'NOT WORKING'), ('NEW', 'NEW')], db_column='status', default='NEW', max_length=15, verbose_name='Working status'),
        ),
        migrations.AddField(
            model_name='systemhostedapplication',
            name='still_functions',
            field=models.BooleanField(db_column='still_functions', default=True, verbose_name='Still functions'),
        ),
    ]
