# Generated by Django 4.0.5 on 2022-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0006_systemhostedapplication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemhostedapplication',
            name='usage_start_date',
            field=models.DateField(blank=True, db_column='usage_start_date', null=True, verbose_name='Usage start date'),
        ),
    ]
