# Generated by Django 4.0.6 on 2022-08-12 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0003_alter_membership_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined', default=datetime.datetime(2022, 8, 12, 9, 36, 25, 1765), verbose_name='Date joined group'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='date_created',
            field=models.DateTimeField(db_column='date_created', default=datetime.datetime(2022, 8, 12, 9, 36, 25, 1765), verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='usergrouppermission',
            name='date_added',
            field=models.DateTimeField(db_column='date_added', default=datetime.datetime(2022, 8, 12, 9, 36, 25, 1765), verbose_name='Date added'),
        ),
    ]
