# Generated by Django 4.0.5 on 2022-07-12 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0007_alter_membership_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined', default=datetime.datetime(2022, 7, 12, 20, 58, 45, 867379), verbose_name='Date joined group'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='date_created',
            field=models.DateTimeField(db_column='date_created', default=datetime.datetime(2022, 7, 12, 20, 58, 45, 867379), verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='usergrouppermission',
            name='date_added',
            field=models.DateTimeField(db_column='date_added', default=datetime.datetime(2022, 7, 12, 20, 58, 45, 867379), verbose_name='Date added'),
        ),
    ]
