# Generated by Django 4.0.6 on 2022-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='environment_check',
            field=models.TextField(db_column='environment_check', default='Dispenser', verbose_name='Environment check'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='ticket_type',
            field=models.CharField(db_column='ticket_type', default='Installation', max_length=250, verbose_name='Ticket type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='areas_serviced',
            field=models.CharField(db_column='areas_serviced', default='Card reader', max_length=250, verbose_name='Areas serviced'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='end_date',
            field=models.DateField(db_column='end_start', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='start_date',
            field=models.DateField(db_column='start_date', verbose_name='Start date'),
        ),
    ]
