# Generated by Django 4.0.6 on 2022-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancelog_environment_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancesparepart',
            name='quantity_used',
        ),
        migrations.RemoveField(
            model_name='maintenancesparepart',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='unit_quantity',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='was_used',
            field=models.BooleanField(db_column='was_used', default=False, verbose_name='Was used'),
        ),
    ]
