# Generated by Django 4.0.6 on 2022-08-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_maintenancesparepart_quantity_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancelog',
            name='sparepart',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='maintenance_log',
            field=models.ForeignKey(blank=True, db_column='maintenance_log_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spareparts_used', to='maintenance.maintenancelog', verbose_name='Maintenance Log'),
        ),
        migrations.DeleteModel(
            name='MaintenanceSparepart',
        ),
    ]
