# Generated by Django 4.0.6 on 2022-08-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0008_alter_atm_recorded_date_and_more'),
        ('maintenance', '0004_remove_maintenancelog_sparepart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='atm',
            field=models.ForeignKey(blank=True, db_column='atm_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atm_logs', to='assets_management.atm', verbose_name='ATM'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='computer',
            field=models.ForeignKey(blank=True, db_column='computer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_logs', to='assets_management.computerlapdesktop', verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='note_counter',
            field=models.ForeignKey(blank=True, db_column='note_counter_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_counter_logs', to='assets_management.biovayanotecountergenerator', verbose_name='Note counter'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='printer_scanner',
            field=models.ForeignKey(blank=True, db_column='printer_scanner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_scanner_logs', to='assets_management.printerscanner', verbose_name='Printer/Scanner'),
        ),
    ]
