# Generated by Django 4.0.5 on 2022-07-17 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestassignment',
            name='opened_date',
            field=models.DateTimeField(db_column='opened_date', default=datetime.datetime(2022, 7, 17, 10, 52, 9, 729309), verbose_name='Opened date'),
        ),
    ]
