# Generated by Django 4.0.6 on 2022-07-30 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestassignment',
            name='opened_date',
            field=models.DateTimeField(db_column='opened_date', default=datetime.datetime(2022, 7, 30, 10, 1, 41, 230848), verbose_name='Opened date'),
        ),
    ]
