# Generated by Django 4.0.6 on 2022-08-05 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestassignment',
            name='opened_date',
            field=models.DateTimeField(db_column='opened_date', default=datetime.datetime(2022, 8, 5, 9, 45, 41, 986557), verbose_name='Opened date'),
        ),
        migrations.AlterField(
            model_name='requestassignment',
            name='request_type',
            field=models.CharField(db_column='request_type', max_length=40, verbose_name='Request type'),
        ),
    ]
