# Generated by Django 4.0.6 on 2022-08-05 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0003_alter_requestassignment_opened_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestassignment',
            name='opened_date',
            field=models.DateTimeField(db_column='opened_date', default=datetime.datetime(2022, 8, 5, 12, 43, 5, 133937), verbose_name='Opened date'),
        ),
    ]
