# Generated by Django 4.0.6 on 2022-08-12 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0004_alter_requestassignment_opened_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestassignment',
            name='opened_date',
            field=models.DateTimeField(db_column='opened_date', default=datetime.datetime(2022, 8, 12, 9, 36, 25, 1765), verbose_name='Opened date'),
        ),
    ]
